name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        include:
          - python-version: "3.11"
            django-version: Django==4.2

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        cd example
        pip install ${{ matrix.django-version }}
        pip install -r requirements/base.txt
    - name: Flake
      run: |
        flake8 --config .config/flake8 fperms_iscore
    - name: Run Tests
      run: |
        coverage run --omit */site-packages/*,*/migrations/*,*/lib/* example/manage.py test issue_tracker.tests --settings=dj.settings -v 2
    - name: Coveralls
      uses: coverallsapp/github-action@v2
      with:
        parallel: true
        flag-name: Unit Test

  coveralls_finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@v2
      with:
        parallel-finished: true
